## chap5. pandas 入門

2023-10-30 ~ 31  

In [1]:
import numpy as np
import pandas as pd

In [2]:
from pandas import Series, DataFrame

### シリーズ(Series)

In [3]:
obj = Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

-5

In [12]:
obj2['d'] = 6

In [13]:
obj2[obj2 >0]

d    6
b    7
c    3
dtype: int64

In [14]:
obj2 *2

d    12
b    14
a   -10
c     6
dtype: int64

In [15]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [16]:
'b' in obj2

True

In [17]:
'e' in obj2

False

ディクショナリ形式のデータがある場合は、それを使ってシリーズを作成することができる


In [18]:
sdata = {'Ohio':35000, 'Texas': 71000, 'Oregon': 16000, 'Uta': 5000}
obj3 = Series(sdata)

In [19]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Uta        5000
dtype: int64

In [21]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Uta': 5000}

In [24]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [25]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [27]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Uta        5000
dtype: int64

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Uta                NaN
dtype: float64

In [30]:
obj4.name = 'popuration'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: popuration, dtype: float64

In [31]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [33]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [34]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### データフレーム(DataFrame)

In [36]:
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [37]:
frame.head(5)

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [38]:
frame.tail(5)

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [41]:
DataFrame(data, columns = ['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [42]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'])
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [43]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [46]:
frame2['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [47]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [48]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [49]:
frame2.iloc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [50]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [51]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [52]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [54]:
frame2['eastern'] = frame2['state'] == 'Ohio'
frame2

year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [55]:
del frame2['eastern']
frame2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [56]:
population = {'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6},
              'Nevada': {2001: 2.4, 2002: 2.9}}

In [57]:
frame3 = DataFrame(population)
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [59]:
frame3.T

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [60]:
DataFrame(population, index=[2001, 2002, 2003])

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [62]:
pdata = {'Ohio':frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [63]:
DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [67]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [68]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [70]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### インデックスオブジェクト

In [71]:
obj = Series(np.arange(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [72]:
index[1:]

Index(['b', 'c'], dtype='object')

In [74]:
labels = pd.Index(np.arange(3))

In [75]:
labels

Index([0, 1, 2], dtype='int32')

In [76]:
obj2 = Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [77]:
obj2.index is labels

True

In [78]:
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [80]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [81]:
'Ohio' in frame3.columns

True

In [83]:
2002 in frame3.index

True

In [84]:
pd.Index(['foo', 'foo', 'bar', 'bar'])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

### pandasの重要な機能

### 再インデックス付け

In [85]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [87]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [88]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [90]:
obj3.reindex(np.arange(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [94]:
frame = DataFrame(np.arange(9).reshape((3, 3)), 
                  index=['a', 'c', 'd'], 
                  columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [95]:
frame2 = frame.reindex(index=['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [96]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [97]:
frame.reindex(states, axis='columns')

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [98]:
frame.loc[['a', 'd', 'c'],['California', 'Texas']]

California  Texas
a           2      1
d           8      7
c           5      4

軸から要素を削除する

In [99]:
obj = Series(np.arange(5.), index=('a', 'b', 'c', 'd', 'e'))
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [100]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [101]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [103]:
data = DataFrame(np.arange(16).reshape((4, 4)), 
                 index=['Ohio', 'Colorado', 'Utah', 'New York'], 
                 columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [104]:
data.drop(index=['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [105]:
data.drop(columns='two')

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

インデックス参照、選択、フィルタリング

In [106]:
obj = Series(np.arange(4.), index=['a', 'b', 'c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [107]:
obj['b']

1.0

In [108]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [109]:
obj[['b', 'c', 'd']]

b    1.0
c    2.0
d    3.0
dtype: float64

In [110]:
obj[[1,3]]

C:\Users\sinis\AppData\Local\Temp\ipykernel_13792\1781339481.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1,3]]


b    1.0
d    3.0
dtype: float64

In [111]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [112]:
obj.loc[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [113]:
data = DataFrame(np.arange(16).reshape((4, 4)), 
                 index=['Ohio', 'Colorado', 'Utah', 'New York'], 
                 columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [114]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [115]:
data[['three', 'four']]

three  four
Ohio          2     3
Colorado      6     7
Utah         10    11
New York     14    15

In [116]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [117]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [118]:
data <  5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [119]:
data[data < 5] = 0

In [120]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [121]:
data.loc['Colorado']

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int32

In [122]:
data.loc[['Colorado', 'New York']]

one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

算術メソッドと穴埋め

In [123]:
df1 = DataFrame(np.arange(12.).reshape((3, 4)), 
                columns=list('abcd'))

In [124]:
df2 = DataFrame(np.arange(20.).reshape((4, 5)),
                columns=list('abcde'))

In [125]:
df2.loc[1, 'b'] = np.nan

In [126]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [127]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [128]:
df1 +df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [129]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [130]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [131]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [132]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [133]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [134]:
arr[0]

array([0., 1., 2., 3.])

In [135]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [136]:
frame = DataFrame(np.arange(12.).reshape((4, 3)), 
                  columns=list('bde'), 
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]

In [137]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [138]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [139]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [140]:
series2 = Series(np.arange(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int32

In [141]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [142]:
series3 = frame['d']

In [143]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [144]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [148]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

関数の適用とマッピング

In [149]:
frame = DataFrame(np.random.standard_normal((4, 3)), 
                  columns=list('bde'), 
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.593214  0.655167 -0.612056
Ohio    1.556166  0.513478  0.163352
Texas   1.622868  2.633069  1.450155
Oregon -0.889957 -1.248906 -1.943696

In [150]:
np.abs(frame)

b         d         e
Utah    0.593214  0.655167  0.612056
Ohio    1.556166  0.513478  0.163352
Texas   1.622868  2.633069  1.450155
Oregon  0.889957  1.248906  1.943696

In [151]:
def f1(x):
    return x.max() - x.min()

In [153]:
frame.apply(f1)

b    2.512825
d    3.881975
e    3.393851
dtype: float64

In [154]:
frame.apply(f1, axis='columns')

Utah      1.267223
Ohio      1.392814
Texas     1.182915
Oregon    1.053739
dtype: float64

In [155]:
def f2(x):
    return Series([x.min(), x.max()], index=['min', 'max'])

In [156]:
frame.apply(f2)

b         d         e
min -0.889957 -1.248906 -1.943696
max  1.622868  2.633069  1.450155

In [157]:
frame.apply(f2, axis='columns')

min       max
Utah   -0.612056  0.655167
Ohio    0.163352  1.556166
Texas   1.450155  2.633069
Oregon -1.943696 -0.889957

In [158]:
def my_format(x):
    return f'{x:.2f}'

In [159]:
frame.applymap(my_format)

C:\Users\sinis\AppData\Local\Temp\ipykernel_13792\1462544007.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(my_format)


b      d      e
Utah    -0.59   0.66  -0.61
Ohio     1.56   0.51   0.16
Texas    1.62   2.63   1.45
Oregon  -0.89  -1.25  -1.94

In [160]:
frame['e'].map(my_format)

Utah      -0.61
Ohio       0.16
Texas      1.45
Oregon    -1.94
Name: e, dtype: object

ソートとランク

In [162]:
obj = Series(np.arange(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int32

In [163]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int32

In [164]:
frame = DataFrame(np.arange(8).reshape((2, 4)), 
                  index=['three', 'one'], 
                  columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [165]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [166]:
frame.sort_index(axis='columns')

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [167]:
frame.sort_index(axis='columns', ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [171]:
frame.sort_index(axis='index').sort_index(axis='columns')

a  b  c  d
one    5  6  7  4
three  1  2  3  0

In [172]:
obj = Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [173]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [174]:
obj = Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [176]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [177]:
obj.sort_values(na_position='first')

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [178]:
frame = DataFrame({'b':[4, 7, -3,2],'a':[0, 1, 0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [180]:
frame.sort_values('b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [181]:
frame.sort_values(['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [183]:
obj = Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [184]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [185]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [186]:
frame = DataFrame({'b':[4.3, 7, -3, 2], 'a':[0, 1, 0, 1], 'c':[-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [187]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

重複したラベルを持つ軸のインデックス

In [188]:
obj = Series(np.arange(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int32

In [189]:
obj.index.is_unique

False

In [190]:
obj['a']

a    0
a    1
dtype: int32

In [191]:
obj['c']

4

In [192]:
df = DataFrame(np.random.standard_normal((5, 3)), 
               index=['a', 'a', 'b', 'b', 'c'])
df

0         1         2
a -1.278992  3.110228 -1.313549
a  0.005700 -0.437798 -0.358906
b  0.184943 -2.198448 -1.012969
b -0.238636  0.269963  0.783226
c  0.871013  1.486327  0.432487

In [193]:
df.loc['b']

0         1         2
b  0.184943 -2.198448 -1.012969
b -0.238636  0.269963  0.783226

In [194]:
df.loc['c']

0    0.871013
1    1.486327
2    0.432487
Name: c, dtype: float64

### 集約と要約統計量の計算

In [195]:
df = DataFrame([[1.4, np.nan,], [7.1, -4.5], 
                [np.nan, np.nan], [0.75, -1.3]], 
                index = ['a', 'b', 'c', 'd'],
                columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [196]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [197]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [198]:
df.sum(axis='index', skipna=False)

one   NaN
two   NaN
dtype: float64

In [199]:
df.mean(axis='columns')

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [200]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [201]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [202]:
obj = Series(['a', 'a', 'b', 'c'] * 4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [203]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

相関と共分散

In [205]:
price = pd.read_pickle('examples/yahoo_price.pkl')

In [206]:
price

AAPL        GOOG         IBM       MSFT
Date                                                     
2010-01-04   27.990226  313.062468  113.304536  25.884104
2010-01-05   28.038618  311.683844  111.935822  25.892466
2010-01-06   27.592626  303.826685  111.208683  25.733566
2010-01-07   27.541619  296.753749  110.823732  25.465944
2010-01-08   27.724725  300.709808  111.935822  25.641571
...                ...         ...         ...        ...
2016-10-17  117.550003  779.960022  154.770004  57.220001
2016-10-18  117.470001  795.260010  150.720001  57.660000
2016-10-19  117.120003  801.500000  151.259995  57.529999
2016-10-20  117.059998  796.969971  151.520004  57.250000
2016-10-21  116.599998  799.369995  149.630005  59.660000

[1714 rows x 4 columns]

In [207]:
volume = pd.read_pickle('examples/yahoo_volume.pkl')
volume

AAPL      GOOG       IBM      MSFT
Date                                               
2010-01-04  123432400   3927000   6155300  38409100
2010-01-05  150476200   6031900   6841400  49749600
2010-01-06  138040000   7987100   5605300  58182400
2010-01-07  119282800  12876600   5840600  50559700
2010-01-08  111902700   9483900   4197200  51197400
...               ...       ...       ...       ...
2016-10-17   23624900   1089500   5890400  23830000
2016-10-18   24553500   1995600  12770600  19149500
2016-10-19   20034600    116600   4632900  22878400
2016-10-20   24125800   1734200   4023100  49455600
2016-10-21   22384800   1260500   4401900  79974200

[1714 rows x 4 columns]

In [210]:
returns = price.pct_change()
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

corrメソッド ..相関係数を求める
covメソッド ..共分散を求める

In [211]:
returns['MSFT'].corr(returns['IBM'])

0.4997636114415114

In [212]:
returns['MSFT'].cov(returns['IBM'])

8.870655479703546e-05

In [213]:
returns.MSFT.corr(returns.IBM)

0.4997636114415114

In [214]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [215]:
returns.cov()

AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

In [216]:
returns.corrwith(returns['IBM'])

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [217]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

一意な値、頻度の確認、所属の確認

In [218]:
obj = Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [219]:
unique = obj.unique()

In [220]:
unique

array(['c', 'a', 'd', 'b'], dtype=object)

In [221]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [222]:
pd.value_counts(obj.to_numpy(), sort=False)

C:\Users\sinis\AppData\Local\Temp\ipykernel_13792\164454357.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj.to_numpy(), sort=False)


c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [223]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [225]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [226]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [227]:
to_match = Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = Series(['c', 'b', 'a'])

In [228]:
indices = pd.Index(unique_vals).get_indexer(to_match)
indices

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [229]:
data = DataFrame({'Qu1': [1, 3, 4, 3, 4], 
                  'Qu2': [2, 3, 1, 2, 3], 
                  'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [231]:
data['Qu1'].value_counts().sort_index()

Qu1
1    1
3    2
4    2
Name: count, dtype: int64

In [232]:
result = data.apply(pd.value_counts).fillna(0)

C:\Users\sinis\AppData\Local\Temp\ipykernel_13792\2451317050.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  result = data.apply(pd.value_counts).fillna(0)


In [233]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [234]:
data = DataFrame({'a': [1, 1, 1, 2, 2], 
                  'b': [0, 0, 1, 0, 0]})
data

a  b
0  1  0
1  1  0
2  1  1
3  2  0
4  2  0

In [235]:
data.value_counts()

a  b
1  0    2
2  0    2
1  1    1
Name: count, dtype: int64