## chap7. データのクリーニングと前処理
2023-11-3 ~ 11-4

In [1]:
import numpy as np
import pandas as pd

In [2]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [3]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [4]:
string_data = pd.Series(['aardvark', np.nan, None, 'avocado'])
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [5]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [6]:
float_data = pd.Series([1, 2, None], dtype='float64')
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [7]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

欠損値を取り除く
```dropna()```

In [8]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [9]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

データフレームオブジェクトの場合、dropnaメソッドは欠損値を1つでも含む行をすべて削除する  

In [10]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.0]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [11]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [12]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [13]:
data[4] = np.nan
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [14]:
data.dropna(axis='columns', how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [15]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))
df

0         1         2
0  0.069959  0.527668 -0.540777
1  0.093694  0.629238  0.776928
2 -0.099559  0.994417 -0.087047
3 -2.123461 -0.187033  0.637999
4  0.689247  0.411480 -0.204930
5 -2.301317  0.421241 -1.748589
6 -1.352554  0.396180  0.323859

In [16]:
df.iloc[:4, 1] = np.nan

In [17]:
df

0         1         2
0  0.069959       NaN -0.540777
1  0.093694       NaN  0.776928
2 -0.099559       NaN -0.087047
3 -2.123461       NaN  0.637999
4  0.689247  0.411480 -0.204930
5 -2.301317  0.421241 -1.748589
6 -1.352554  0.396180  0.323859

In [18]:
df.iloc[:2, 2] = np.nan
df

0         1         2
0  0.069959       NaN       NaN
1  0.093694       NaN       NaN
2 -0.099559       NaN -0.087047
3 -2.123461       NaN  0.637999
4  0.689247  0.411480 -0.204930
5 -2.301317  0.421241 -1.748589
6 -1.352554  0.396180  0.323859

In [19]:
df.dropna()

0         1         2
4  0.689247  0.411480 -0.204930
5 -2.301317  0.421241 -1.748589
6 -1.352554  0.396180  0.323859

In [20]:
df.dropna(thresh=2)

0         1         2
2 -0.099559       NaN -0.087047
3 -2.123461       NaN  0.637999
4  0.689247  0.411480 -0.204930
5 -2.301317  0.421241 -1.748589
6 -1.352554  0.396180  0.323859

欠損値を穴埋めする
```fillna()```

In [21]:
df.fillna(0)

0         1         2
0  0.069959  0.000000  0.000000
1  0.093694  0.000000  0.000000
2 -0.099559  0.000000 -0.087047
3 -2.123461  0.000000  0.637999
4  0.689247  0.411480 -0.204930
5 -2.301317  0.421241 -1.748589
6 -1.352554  0.396180  0.323859

In [22]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  0.069959  0.500000  0.000000
1  0.093694  0.500000  0.000000
2 -0.099559  0.500000 -0.087047
3 -2.123461  0.500000  0.637999
4  0.689247  0.411480 -0.204930
5 -2.301317  0.421241 -1.748589
6 -1.352554  0.396180  0.323859

In [23]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df

0         1         2
0 -0.027837 -0.645542  2.210684
1 -1.027990 -1.733594 -0.256182
2 -0.065047 -0.021815 -0.394266
3  1.890158 -0.218027 -0.433890
4  0.037685 -0.920697  0.070893
5 -0.247143 -0.411017  0.007249

In [24]:
df.iloc[2:, 1] = np.nan

In [25]:
df

0         1         2
0 -0.027837 -0.645542  2.210684
1 -1.027990 -1.733594 -0.256182
2 -0.065047       NaN -0.394266
3  1.890158       NaN -0.433890
4  0.037685       NaN  0.070893
5 -0.247143       NaN  0.007249

In [26]:
df.iloc[4: ,2] = np.nan
df

0         1         2
0 -0.027837 -0.645542  2.210684
1 -1.027990 -1.733594 -0.256182
2 -0.065047       NaN -0.394266
3  1.890158       NaN -0.433890
4  0.037685       NaN       NaN
5 -0.247143       NaN       NaN

In [27]:
df.fillna(method='ffill')

C:\Users\sinis\AppData\Local\Temp\ipykernel_12112\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')


0         1         2
0 -0.027837 -0.645542  2.210684
1 -1.027990 -1.733594 -0.256182
2 -0.065047 -1.733594 -0.394266
3  1.890158 -1.733594 -0.433890
4  0.037685 -1.733594 -0.433890
5 -0.247143 -1.733594 -0.433890

In [28]:
df.fillna(method='ffill', limit=2)

C:\Users\sinis\AppData\Local\Temp\ipykernel_12112\2719175769.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', limit=2)


0         1         2
0 -0.027837 -0.645542  2.210684
1 -1.027990 -1.733594 -0.256182
2 -0.065047 -1.733594 -0.394266
3  1.890158 -1.733594 -0.433890
4  0.037685       NaN -0.433890
5 -0.247143       NaN -0.433890

In [29]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [30]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

### データの変形

重複の除去

In [31]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 +['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [32]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [33]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [34]:
data['v1'] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [35]:
data.drop_duplicates(subset='k1')

k1  k2  v1
0  one   1   0
1  two   1   1

In [36]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

関数やマッピングを用いたデータの変換

In [37]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'pastrami', 'corned beef', 'bacon', 'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5,6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [38]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

In [39]:
data['animals'] = data['food'].map(meat_to_animal)
data

food  ounces animals
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [40]:
def get_animal(x):
    return meat_to_animal[x]

In [41]:
data['food'].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

値の置き換え
```replace()```

In [42]:
data = pd.Series([1., -999, 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [43]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [44]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [45]:
data.replace([-999,-1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [46]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

軸のインデックスの名前を変更する

In [47]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)), 
                    index=['Ohio', 'Colorado', 'New York'], 
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [48]:
def transform(x):
    return x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [49]:
data.index = data.index.map(transform)

In [50]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [51]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [52]:
data.rename(index={'OHIO': 'INDIANA'}, columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

離散化とビニング  
```pd.cut()```

In [53]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [54]:
bins = [18, 25, 35, 60, 100]

In [55]:
age_categories = pd.cut(ages, bins)
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [56]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [57]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [58]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [59]:
pd.value_counts(age_categories)

C:\Users\sinis\AppData\Local\Temp\ipykernel_12112\3010498523.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)


(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [60]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [61]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [62]:
data = np.random.uniform(size=20)
data

array([0.07764656, 0.99473003, 0.73811582, 0.66792482, 0.72604878,
       0.94200032, 0.84514351, 0.44131678, 0.59366147, 0.47789128,
       0.74710171, 0.5432872 , 0.50929898, 0.53184131, 0.76874452,
       0.31534958, 0.60220796, 0.51030143, 0.53699512, 0.68350028])

In [63]:
pd.cut(data, 4, precision=2)

[(0.077, 0.31], (0.77, 0.99], (0.54, 0.77], (0.54, 0.77], (0.54, 0.77], ..., (0.31, 0.54], (0.54, 0.77], (0.31, 0.54], (0.54, 0.77], (0.54, 0.77]]
Length: 20
Categories (4, interval[float64, right]): [(0.077, 0.31] < (0.31, 0.54] < (0.54, 0.77] < (0.77, 0.99]]

In [64]:
data = np.random.standard_normal(1000)


In [65]:
quatiles = pd.qcut(data, 4, precision=2)
quatiles

[(0.72, 2.96], (0.016, 0.72], (-0.66, 0.016], (0.016, 0.72], (-0.66, 0.016], ..., (-0.66, 0.016], (0.016, 0.72], (0.72, 2.96], (0.72, 2.96], (0.016, 0.72]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.21, -0.66] < (-0.66, 0.016] < (0.016, 0.72] < (0.72, 2.96]]

In [66]:
pd.value_counts(quatiles)

C:\Users\sinis\AppData\Local\Temp\ipykernel_12112\2209087811.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quatiles)


(-3.21, -0.66]    250
(-0.66, 0.016]    250
(0.016, 0.72]     250
(0.72, 2.96]      250
Name: count, dtype: int64

In [67]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.1959999999999997, -1.265]    100
(-1.265, 0.0164]                 400
(0.0164, 1.303]                  400
(1.303, 2.962]                   100
Name: count, dtype: int64

外れ値の検出と除去

In [68]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.007646     0.026108     0.083632    -0.015060
std       1.017060     1.017973     0.989015     0.965700
min      -3.731095    -3.205327    -3.330037    -3.655213
25%      -0.649746    -0.630017    -0.609741    -0.637869
50%      -0.014320     0.026500     0.092567    -0.034741
75%       0.695808     0.742609     0.776058     0.629544
max       3.262533     3.444261     3.160191     3.808428

In [69]:
col = data[2]

In [70]:
col[col.abs() >3]

405    3.118900
488   -3.330037
605    3.160191
Name: 2, dtype: float64

In [71]:
data[(data.abs() > 3).any(axis='columns')]

0         1         2         3
15  -3.731095  0.817121  0.836520  0.334027
128 -0.566841  3.422254 -0.291851  1.756984
189  3.262533  0.020078  0.003367  0.397774
310 -0.219495 -0.273886 -0.077142 -3.655213
341 -1.351275 -3.049394 -1.578341  0.666689
350  0.391345  0.527603  1.176102  3.362418
381 -1.645515 -3.205327  1.095873  0.353648
383  1.058151  0.459076  1.894058 -3.006920
405  1.190299 -0.123632  3.118900  0.608220
488  0.675768  0.043922 -3.330037 -0.280848
605 -1.052187  0.712989  3.160191  0.194132
765  1.843057  1.541744 -1.006270  3.808428
821  1.048415  3.403207 -0.628858  1.882799
933  0.833689  3.444261  0.678059  0.980334

In [72]:
data[data.abs() > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.008115     0.025093     0.083683    -0.015569
std       1.013820     1.013204     0.987084     0.959341
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.649746    -0.630017    -0.609741    -0.637869
50%      -0.014320     0.026500     0.092567    -0.034741
75%       0.695808     0.742609     0.776058     0.629544
max       3.000000     3.000000     3.000000     3.000000

順列（ランダムな並べ替え）やランダムサンプリング  
```np.random.permutation()```

In [73]:
df = pd.DataFrame(np.arange(5 * 7).reshape(5, 7))
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [74]:
sampler = np.random.permutation(5)
sampler

array([3, 1, 2, 0, 4])

In [75]:
df.take(sampler)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34

In [76]:
df.iloc[sampler]

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34

In [77]:
column_sampler = np.random.permutation(7)
column_sampler

array([1, 2, 0, 3, 6, 5, 4])

In [78]:
df.take(column_sampler, axis='columns')

1   2   0   3   6   5   4
0   1   2   0   3   6   5   4
1   8   9   7  10  13  12  11
2  15  16  14  17  20  19  18
3  22  23  21  24  27  26  25
4  29  30  28  31  34  33  32

In [79]:
df.sample(n=3)

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27

In [80]:
choices = pd.Series([5, 7, -1, 6, 4])
choices.sample(n=10, replace = True)

4    4
4    4
3    6
3    6
0    5
1    7
1    7
4    4
2   -1
1    7
dtype: int64

標識変数やダミー変数の計算

In [81]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [82]:
pd.get_dummies(df['key'])

a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [85]:
dummies = pd.get_dummies(df['key'], prefix='key')
dummies

key_a  key_b  key_c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [84]:
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [86]:
mnames = ['movie_id', 'title', 'genres']

In [87]:
movies = pd.read_table('datasets/movielens/movies.dat', sep='::', header=None, names=mnames, engine='python')

In [88]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [89]:
dummies = movies['genres'].str.get_dummies('|')

In [90]:
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [91]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [92]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

pandas.cutなどの離散化関数とpandas.get_dummiesを組み合わせて使う方法

In [93]:
np.random.seed(12345) # 実行例を再現可能にするためシードを固定

In [94]:
values = np.random.uniform(size=10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [95]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [99]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

### 拡張データ型

In [100]:
s = pd.Series([1, 2, 3, None])
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [102]:
s.dtype

dtype('float64')

In [105]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [106]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

### 文字列操作

In [107]:
val = 'a,b, guido'

In [108]:
val.split(',')

['a', 'b', ' guido']

In [109]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [110]:
first, second, third = pieces
first + '::' + second + '::' + third

'a::b::guido'

In [111]:
'::'.join(pieces)

'a::b::guido'

In [113]:
'guido' in val

True

In [115]:
val.index(',')

1

In [117]:
val.find(':')

-1

In [118]:
val.count(',')

2

In [119]:
val.replace(',', '::')

'a::b:: guido'

In [120]:
val.replace(',', '')

'ab guido'

正規表現

In [121]:
import re

In [122]:
text = 'foo  bar\t baz \tqux'

In [123]:
re.split(r'\s+', text)

['foo', 'bar', 'baz', 'qux']

In [126]:
regex = re.compile(r'\s+')
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [127]:
regex.findall(text)

['  ', '\t ', ' \t']

pandasの文字列関数

In [128]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com', 'Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [129]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [130]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [131]:
data_as_string_ext = data.astype('string')
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [132]:
data_as_string_ext.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [133]:
data_as_string_ext.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [134]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9._]+)\.([A-Z]{2,4})'

In [135]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [136]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [137]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [138]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [139]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [140]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [141]:
values = pd.Series(['apple', 'orange', 'apple', 'apple'] * 2)
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [142]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [143]:
pd.value_counts(values)

C:\Users\sinis\AppData\Local\Temp\ipykernel_12112\3297668723.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)


apple     6
orange    2
Name: count, dtype: int64

In [144]:
values = pd.Series([0, 1, 0, 0] * 2)
dim = pd.Series(['apple', 'orange'])

In [145]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [146]:
dim

0     apple
1    orange
dtype: object

In [147]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

pandasにおけるカテゴリ拡張データ型

In [150]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [151]:
N = len(fruits)

In [153]:
rng = np.random.default_rng(seed=12345)

In [156]:
df = pd.DataFrame({'fruit': fruits, 
                   'basket_id': np.arange(N), 
                   'count': rng.integers(3, 15, size=N), 
                   'weight': rng.uniform(0, 4, size=N)}, 
                   columns=['basket_id', 'fruit', 'count', 'weight'])

In [157]:
df

basket_id   fruit  count    weight
0          0   apple     14  2.691024
1          1  orange      7  3.767211
2          2   apple     13  0.992983
3          3   apple      6  3.795525
4          4   apple      9  2.668950
5          5  orange     10  0.383592
6          6   apple      5  1.767359
7          7   apple      5  3.545920

In [158]:
fruit_cat = df['fruit'].astype('category')

In [159]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [160]:
c = fruit_cat.array
c

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']
Categories (2, object): ['apple', 'orange']

In [161]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [163]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [164]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [165]:
df['fruit'] = df['fruit'].astype('category')

In [166]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [167]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [168]:
categories = ['foo', 'bar', 'baz']

In [169]:
codes = [0, 1, 2, 0, 0, 1]

In [170]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [171]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [172]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [174]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

カテゴリを用いた計算

In [175]:
rng = np.random.default_rng(seed=12345)
draws = rng.standard_normal(1000)
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [176]:
bins = pd.qcut(draws, 4)
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [177]:
bins.value_counts()

(-3.121, -0.675]    250
(-0.675, 0.0134]    250
(0.0134, 0.687]     250
(0.687, 3.211]      250
Name: count, dtype: int64

In [178]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [179]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [182]:
bins = pd.Series(bins, name='quatile')

In [183]:
result = (pd.Series(draws)
          .groupby(bins)
          .agg(['count', 'min', 'max'])
          .reset_index())

C:\Users\sinis\AppData\Local\Temp\ipykernel_12112\2185482846.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(bins)


In [184]:
result

quatile  count       min       max
0      Q1    250 -3.119609 -0.678494
1      Q2    250 -0.673305  0.008009
2      Q3    250  0.018753  0.686183
3      Q4    250  0.688282  3.211418

In [186]:
result['quatile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quatile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

カテゴリ変数を用いた処理性能の改善

In [187]:
N = 10_000_000

In [188]:
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N//4))

In [189]:
categories = labels.astype('category')

In [191]:
labels.memory_usage(deep=True)

600000132

In [192]:
categories.memory_usage(deep=True)

10000544

In [193]:
%time _ = labels.astype('category')

CPU times: total: 312 ms
Wall time: 389 ms


In [194]:
%timeit labels.value_counts()

288 ms ± 4.07 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [195]:
%timeit categories.value_counts()

43.2 ms ± 5.55 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


カテゴリメソッド

In [196]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [197]:
cat_s = s.astype('category')

In [198]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [199]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [200]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [201]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [202]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [203]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [204]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [205]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [206]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]

In [207]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [208]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

モデリング用のダミー変数の作成

In [209]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] *2, dtype='category')

In [210]:
pd.get_dummies(cat_s)

a      b      c      d
0   True  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True
4   True  False  False  False
5  False   True  False  False
6  False  False   True  False
7  False  False  False   True

### まとめ

データの前処理を効率良く行えるようになると、分析の準備にかける時間が減り、その時間をデータ分析に費やせるようになるため、かなり生産性が向上します。  
この章ではたくさんのツールを使ってみましたが、幅広い内容を網羅できたというわけでは、決してありません。次の章では、データの結合やグループ化といったpandasの機能を見ていきましょう。