## 付録A NumPy：応用編

2023-11-16 ~ 11-17  

### Ａ．1 ndarrayオブジェクトの内部構造

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math

In [3]:
rng = np.random.default_rng(seed=12345)

In [4]:
np.ones((10, 5)).shape

(10, 5)

A.1.1 NumPyのデータ型の階層構造

### A.2 配列操作：応用編

A.2.1 配列の形状の再成形

In [10]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [12]:
arr.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [13]:
arr.reshape(4,2).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

形状を定める次元のひとつに-1を指定することもできる

In [14]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
arr.reshape(5, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [17]:
other_arr = np.ones((3, 5))
other_arr.shape

(3, 5)

In [19]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

平坦化(flatten)とレイベリング(ravel)

In [20]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [21]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

A.2.2 C型の順序(行優先)とFORTRAN型(列優先)の順序

In [22]:
arr.ravel('F')

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

A.2.3 配列の連結と分割

In [24]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [25]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [27]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [29]:
arr = rng.standard_normal((5, 2))
arr

array([[-1.42382504,  1.26372846],
       [-0.87066174, -0.25917323],
       [-0.07534331, -0.74088465],
       [-1.3677927 ,  0.6488928 ],
       [ 0.36105811, -1.95286306]])

In [30]:
first, second, third = np.split(arr, [1, 3])

In [31]:
first

array([[-1.42382504,  1.26372846]])

In [32]:
second

array([[-0.87066174, -0.25917323],
       [-0.07534331, -0.74088465]])

In [33]:
third

array([[-1.3677927 ,  0.6488928 ],
       [ 0.36105811, -1.95286306]])

A.2.3.1 配列を連結するためのヘルパー関数：r_とc_

In [34]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [35]:
arr1 = arr.reshape((3, 2))
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [36]:
arr2 = rng.standard_normal((3, 2))
arr2

array([[ 2.34740965,  0.96849691],
       [-0.75938718,  0.90219827],
       [-0.46695317, -0.06068952]])

In [37]:
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 2.34740965,  0.96849691],
       [-0.75938718,  0.90219827],
       [-0.46695317, -0.06068952]])

In [38]:
np.c_[arr1, arr2]

array([[ 0.        ,  1.        ,  2.34740965,  0.96849691],
       [ 2.        ,  3.        , -0.75938718,  0.90219827],
       [ 4.        ,  5.        , -0.46695317, -0.06068952]])

In [40]:
np.c_[1:6, -10:-5, 3: 8]

array([[  1, -10,   3],
       [  2,  -9,   4],
       [  3,  -8,   5],
       [  4,  -7,   6],
       [  5,  -6,   7]])

In [42]:
np.r_[0: 5, 5:10, 10,15]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 15])

### A.2.4 要素の繰り返し： tileとrepeat

In [43]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [44]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [46]:
arr.repeat([2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [47]:
arr = rng.standard_normal((2, 2))
arr

array([[ 0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899]])

In [50]:
arr.repeat(2, axis=0)

array([[ 0.78884434, -1.25666813],
       [ 0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899],
       [ 0.57585751,  1.39897899]])

In [51]:
arr.repeat([2, 3], axis=0)

array([[ 0.78884434, -1.25666813],
       [ 0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899],
       [ 0.57585751,  1.39897899],
       [ 0.57585751,  1.39897899]])

In [52]:
arr.repeat([2, 3], axis=1)

array([[ 0.78884434,  0.78884434, -1.25666813, -1.25666813, -1.25666813],
       [ 0.57585751,  0.57585751,  1.39897899,  1.39897899,  1.39897899]])

tile

In [53]:
arr

array([[ 0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899]])

In [54]:
np.tile(arr, 2)

array([[ 0.78884434, -1.25666813,  0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899,  0.57585751,  1.39897899]])

In [55]:
np.tile(arr, (2, 1))

array([[ 0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899],
       [ 0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899]])

In [56]:
np.tile(arr, (2, 2))

array([[ 0.78884434, -1.25666813,  0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899,  0.57585751,  1.39897899],
       [ 0.78884434, -1.25666813,  0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899,  0.57585751,  1.39897899]])

A.2.5 ファンシーインデックス参照の別法： takeとput

In [57]:
arr = np.arange(10) * 100
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [58]:
inds = [7, 1, 2, 6]

In [59]:
arr[inds]

array([700, 100, 200, 600])

In [60]:
arr.take(inds)

array([700, 100, 200, 600])

In [65]:
arr.put(inds, [7, 1, 2, 6])
arr

array([  0,   1,   2, 300, 400, 500,   6,   7, 800, 900])

In [66]:
inds = [2, 0, 2, 1]

In [67]:
arr = rng.standard_normal((2, 4))
arr

array([[ 1.32229806, -0.29969852,  0.90291934, -1.62158273],
       [-0.15818926,  0.44948393, -1.34360107, -0.08168759]])

In [68]:
arr.take(inds, axis=1)

array([[ 0.90291934,  1.32229806,  0.90291934, -0.29969852],
       [-1.34360107, -0.15818926, -1.34360107,  0.44948393]])

### A.3 ブロードキャスト

ブロードキャストとは、形状の異なる２つの配列に対する演算の方法を規定する概念

In [69]:
arr = np.arange(5)

In [70]:
arr*4

array([ 0,  4,  8, 12, 16])

In [71]:
arr = rng.standard_normal((4,3))
arr

array([[ 1.72473993,  2.61815943,  0.77736134],
       [ 0.8286332 , -0.95898831, -1.20938829],
       [-1.41229201,  0.54154683,  0.7519394 ],
       [-0.65876032, -1.22867499,  0.25755777]])

In [77]:
arr.mean(0)

array([0.1205802 , 0.24301074, 0.14436756])

In [79]:
demeaned = arr - arr.mean(0)
demeaned

array([[ 1.60415973,  2.37514869,  0.63299379],
       [ 0.708053  , -1.20199905, -1.35375584],
       [-1.53287221,  0.29853609,  0.60757184],
       [-0.77934052, -1.47168573,  0.11319021]])

In [80]:
demeaned.mean(0)

array([ 5.55111512e-17, -1.11022302e-16,  0.00000000e+00])

A.3.1 他の軸へのブロードキャスト

In [81]:
arr = np.zeros((4, 4))

In [84]:
arr_3d = arr[:, np.newaxis, :]

In [86]:
arr_3d.shape

(4, 1, 4)

In [87]:
arr_1d = rng.standard_normal(3)
arr_1d

array([ 0.31290292, -0.13081169,  1.26998312])

In [88]:
arr_1d[:, np.newaxis]

array([[ 0.31290292],
       [-0.13081169],
       [ 1.26998312]])

In [89]:
arr_1d[np.newaxis, :]

array([[ 0.31290292, -0.13081169,  1.26998312]])

In [90]:
arr = rng.standard_normal((3, 4, 5))

In [91]:
depth_means = arr.mean(2)
depth_means

array([[ 0.04314136,  0.27468984, -0.18852342, -0.20137996],
       [-0.57324159, -0.54671393,  0.11832783, -0.63005577],
       [ 0.09723001,  0.59537117,  0.03307289, -0.6002202 ]])

In [92]:
demeaned = arr - depth_means[:, :, np.newaxis]
demeaned.mean(2)

array([[ 4.44089210e-17, -1.11022302e-17,  8.88178420e-17,
        -1.66533454e-17],
       [ 2.22044605e-17, -4.44089210e-17, -2.22044605e-17,
        -4.44089210e-17],
       [ 4.44089210e-17,  6.66133815e-17,  0.00000000e+00,
         8.88178420e-17]])

A.3.2 ブロードキャストによる配列への値の設定

In [94]:
arr = np.zeros((4, 3))

In [96]:
arr[:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [97]:
col = np.array([1.28, -0.42, 0.44, 1.6])

In [98]:
arr[:] = col[:, np.newaxis]

In [99]:
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [100]:
arr[:2] = [[-1.37], [0.509]]

In [101]:
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

### A.4 ufuncの使い方：応用編

A4.1 ufuncのインスタントメソッド

In [102]:
arr = np.arange(10)

In [103]:
np.add.reduce(arr)

45

In [104]:
arr.sum()

45

In [108]:
my_rng = np.random.default_rng(12346)

In [109]:
arr = my_rng.standard_normal((5, 5))

In [110]:
arr

array([[-0.903889  ,  0.15713146,  0.89761199, -0.76219554, -0.17625556],
       [ 0.05303172, -1.62844028, -0.17753333,  1.96360352,  1.78125478],
       [-0.87971984, -1.69847913, -1.81891091,  0.11895453, -0.44409513],
       [ 0.76911421, -0.03433778,  0.39252776,  0.75891811, -0.07045967],
       [ 1.04984775,  1.02967072, -0.42005533,  0.78626627,  0.96124929]])

In [111]:
arr[::2].sort(1)

In [112]:
arr[:, :-1] < arr[:, 1:]

array([[ True,  True,  True,  True],
       [False,  True,  True, False],
       [ True,  True,  True,  True],
       [False,  True,  True, False],
       [ True,  True,  True,  True]])

In [113]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

array([ True, False,  True, False,  True])

In [114]:
arr = np.arange(15).reshape((3, 5))

In [115]:
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [117]:
arr = np.arange(3).repeat([1, 2, 2])
arr

array([0, 1, 1, 2, 2])

In [118]:
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [119]:
x, y = rng.standard_normal((3, 4)), rng.standard_normal(5)

In [121]:
result = np.subtract.outer(x,y)
result.shape

(3, 4, 5)

In [122]:
arr = np.arange(10)

In [123]:
np.add.reduceat(arr,[0, 5, 8])

array([10, 18, 17])

In [124]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [125]:
np.add.reduceat(arr, [0, 2, 4], axis=1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]])

A.4.2 Pythonで新しいufuncを書く方法

In [126]:
def add_elements(x, y):
    return x + y

In [128]:
add_them = np.frompyfunc(add_elements, 2, 1)
add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [129]:
add_them = np.vectorize(add_elements, otypes=[np.float64])
add_them(np.arange(8), np.arange(8))

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [130]:
arr = rng.standard_normal(10_000)

In [131]:
%timeit add_them(arr, arr)

1.2 ms ± 4.59 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [132]:
%timeit np.add(arr, arr)

2.72 µs ± 35.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## A.5 構造化配列とレコード配列

In [134]:
dtype = [('x', np.float64), ('y', np.int32)]

In [135]:
sarr = np.array([(1.5, 6), (3.146, -2)], dtype=[('x', '<f8'), ('y', '<i4')])

In [136]:
sarr

array([(1.5  ,  6), (3.146, -2)], dtype=[('x', '<f8'), ('y', '<i4')])

In [137]:
sarr[0]

(1.5, 6)

In [138]:
sarr[0]['y']

6

In [139]:
sarr['x']

array([1.5  , 3.146])

A.5.1 入れ子構造を持つデータ型と多次元フィールド

In [140]:
dtype = [('x', np.int64, 3), ('y', np.int32)]

In [141]:
arr = np.zeros(4, dtype=dtype)
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)],
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [142]:
arr[0]['x']

array([0, 0, 0], dtype=int64)

In [143]:
arr['x']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [150]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]

In [151]:
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)

In [152]:
data['x']

array([(1., 2.), (3., 4.)], dtype=[('a', '<f8'), ('b', '<f4')])

In [153]:
data['y']

array([5, 6])

In [155]:
data['x']['a']

array([1., 3.])

A.5.2 構造化配列を使うべき理由

### A.6 ソートについてさらに詳しく

In [156]:
arr = rng.standard_normal(6)
arr

array([-0.52183471, -0.47451353, -0.16487175, -0.93190851,  0.03003636,
       -1.15533009])

In [157]:
arr.sort()

In [158]:
arr

array([-1.15533009, -0.93190851, -0.52183471, -0.47451353, -0.16487175,
        0.03003636])

In [159]:
arr = rng.standard_normal((3, 5))
arr

array([[-1.19558568,  0.46914309, -0.35978023,  1.03591571,  0.22672235],
       [-0.74479832, -0.59313793, -1.055009  , -0.06826983,  0.45795065],
       [-0.07002967,  0.14616063, -0.9943506 ,  1.14361991,  0.5025894 ]])

In [160]:
arr[:,0].sort()
arr

array([[-1.19558568,  0.46914309, -0.35978023,  1.03591571,  0.22672235],
       [-0.74479832, -0.59313793, -1.055009  , -0.06826983,  0.45795065],
       [-0.07002967,  0.14616063, -0.9943506 ,  1.14361991,  0.5025894 ]])

In [161]:
arr = rng.standard_normal(5)
arr

array([ 0.89812774, -1.17039613, -0.26857518, -0.79595321,  1.45222994])

In [163]:
np.sort(arr)

array([-1.17039613, -0.79595321, -0.26857518,  0.89812774,  1.45222994])

In [165]:
arr

array([ 0.89812774, -1.17039613, -0.26857518, -0.79595321,  1.45222994])

In [166]:
arr = rng.standard_normal((3, 5))
arr

array([[-0.25351976,  2.11834357,  0.36340947, -0.62451153,  1.12789103],
       [ 1.61635997, -0.22872843, -0.62009458, -0.11432382, -1.20673403],
       [-1.08719255, -2.15177088, -0.62873036, -1.31990725,  0.08304824]])

In [167]:
arr.sort(axis=1)

In [168]:
arr

array([[-0.62451153, -0.25351976,  0.36340947,  1.12789103,  2.11834357],
       [-1.20673403, -0.62009458, -0.22872843, -0.11432382,  1.61635997],
       [-2.15177088, -1.31990725, -1.08719255, -0.62873036,  0.08304824]])

逆順のsort(列)

In [169]:
arr[:, ::-1]

array([[ 2.11834357,  1.12789103,  0.36340947, -0.25351976, -0.62451153],
       [ 1.61635997, -0.11432382, -0.22872843, -0.62009458, -1.20673403],
       [ 0.08304824, -0.62873036, -1.08719255, -1.31990725, -2.15177088]])

In [170]:
arr

array([[-0.62451153, -0.25351976,  0.36340947,  1.12789103,  2.11834357],
       [-1.20673403, -0.62009458, -0.22872843, -0.11432382,  1.61635997],
       [-2.15177088, -1.31990725, -1.08719255, -0.62873036,  0.08304824]])

A.6.1 間接ソート： argsortとlexsort

In [171]:
values = np.array([5, 0, 1, 3, 2])
indexer = values.argsort()

In [172]:
indexer

array([1, 2, 4, 3, 0], dtype=int64)

In [173]:
values[indexer]

array([0, 1, 2, 3, 5])

In [174]:
arr = rng.standard_normal((3, 5))
arr

array([[ 0.20170741,  0.91728215,  0.17643823, -0.29339201,  1.16213389],
       [-0.75033171, -2.1267841 , -1.39102406, -0.49224676,  0.45052254],
       [ 0.89260435, -1.04793665,  0.95532342,  0.29355494,  0.53794446]])

In [175]:
arr[0] = values
arr

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [-0.75033171, -2.1267841 , -1.39102406, -0.49224676,  0.45052254],
       [ 0.89260435, -1.04793665,  0.95532342,  0.29355494,  0.53794446]])

In [176]:
arr[:, arr[0].argsort()]

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [-2.1267841 , -1.39102406,  0.45052254, -0.49224676, -0.75033171],
       [-1.04793665,  0.95532342,  0.53794446,  0.29355494,  0.89260435]])

In [181]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walter'])

In [182]:
sorter = np.lexsort((first_name, last_name))

In [183]:
sorter

array([1, 2, 3, 0, 4], dtype=int64)

In [184]:
list(zip(last_name[sorter], first_name[sorter]))

[('Arnold', 'Jane'),
 ('Arnold', 'Steve'),
 ('Jones', 'Bill'),
 ('Jones', 'Bob'),
 ('Walter', 'Barbara')]

A.6.2 使用可能な他のソートアルゴリズム

In [185]:
values = np.array(['2:first', '2:second', '1:first', '1:second', '1:third'])
key = np.array([2, 2, 1, 1, 1])

In [186]:
indexer = key.argsort(kind='mergesort')
indexer

array([2, 3, 4, 0, 1], dtype=int64)

In [187]:
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'],
      dtype='<U8')

A.6.3 配列の一部分をソートする

In [188]:
rng = np.random.default_rng(12345)

In [189]:
arr = rng.standard_normal(20)
arr

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331,
       -0.74088465, -1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306,
        2.34740965,  0.96849691, -0.75938718,  0.90219827, -0.46695317,
       -0.06068952,  0.78884434, -1.25666813,  0.57585751,  1.39897899])

In [190]:
np.partition(arr, 3)

array([-1.95286306, -1.42382504, -1.3677927 , -1.25666813, -0.87066174,
       -0.75938718, -0.74088465, -0.06068952,  0.36105811, -0.07534331,
       -0.25917323, -0.46695317,  0.57585751,  0.90219827,  0.96849691,
        0.6488928 ,  0.78884434,  1.26372846,  1.39897899,  2.34740965])

In [193]:
indices = np.argpartition(arr,3)
indices

array([ 9,  0,  6, 17,  2, 12,  5, 15,  8,  4,  3, 14, 18, 13, 11,  7, 16,
        1, 19, 10], dtype=int64)

In [196]:
arr.take(indices)

array([-1.95286306, -1.42382504, -1.3677927 , -1.25666813, -0.87066174,
       -0.75938718, -0.74088465, -0.06068952,  0.36105811, -0.07534331,
       -0.25917323, -0.46695317,  0.57585751,  0.90219827,  0.96849691,
        0.6488928 ,  0.78884434,  1.26372846,  1.39897899,  2.34740965])

A.6.4 numpy.searchsorted: ソート済みの配列内で要素を探す

In [197]:
arr = np.array([0, 1, 7, 12, 15])

In [198]:
arr.searchsorted(9)

3

In [199]:
arr.searchsorted([0, 8, 11, 16])

array([0, 3, 3, 5], dtype=int64)

In [200]:
data = np.floor(rng.uniform(0, 10_000, size=50))
bins = np.array([0, 100, 1000, 5000, 10000])

In [201]:
data

array([ 815., 1598., 3401., 4651., 2664., 8157., 1932., 1294.,  916.,
       5985., 8547., 6016., 9319., 7247., 8605., 9293., 5461., 9376.,
       4949., 2737., 4517., 6650., 3308., 9034., 2570., 3398., 2588.,
       3554.,   50., 6286., 2823.,  680., 6168., 1763., 3043., 4408.,
       1502., 2179., 4743., 4763., 2552., 2975., 2790., 2605., 4827.,
       2119., 4956., 2462., 8384., 1801.])

In [202]:
labels = bins.searchsorted(data)
labels

array([2, 3, 3, 3, 3, 4, 3, 3, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 4,
       3, 4, 3, 3, 3, 3, 1, 4, 3, 2, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 4, 3], dtype=int64)

In [204]:
pd.Series(data).groupby(labels).count()

1     1
2     3
3    31
4    15
dtype: int64

### A.4.7 Numbaを用いて高速なNumPy関数を書く

In [205]:
def mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count += 1
    return result / count

In [206]:
x = rng.standard_normal(10_000_000)
y = rng.standard_normal(10_000_000)

In [207]:
%timeit mean_distance(x,y)

2.73 s ± 49.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [208]:
%timeit (x-y).mean()

39.6 ms ± 1.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [210]:
import numba as nb

In [211]:
numba_mean_distance = nb.jit(mean_distance)

C:\Users\sinis\AppData\Local\Temp\ipykernel_19904\1849390953.py:1: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  numba_mean_distance = nb.jit(mean_distance)


In [212]:
%timeit numba_mean_distance(x,y)

11.5 ms ± 214 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


A.7.1 独自定義のnumpy.ufuncオブジェクトをNumbaを用いて作成する

In [213]:
from numba import vectorize

In [214]:
@vectorize
def nb_add(x, y):
    return x + y

In [215]:
x = np.arange(10)
nb_add(x, x)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int64)

### A.8 配列の入出力： 応用編

A.8.1 メモリマップファイル

In [226]:
mmap = np.memmap('mymap', dtype='float64', mode='w+', shape=(10_000, 10_000))
mmap

memmap([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [227]:
section = mmap[:5]

In [228]:
section[:] = rng.standard_normal((5, 10000))

In [229]:
mmap.flush()

In [230]:
mmap

memmap([[ 0.87261505, -0.43904416,  0.36104378, ..., -0.58223029,
          1.77299113, -0.06148116],
        [ 0.19793309,  2.54419456,  0.9167002 , ...,  0.17414909,
          0.8363528 , -0.64138733],
        [-0.86714563,  1.35076286,  0.00715899, ...,  0.08768643,
          1.79289497, -2.03982074],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]])

In [231]:
del mmap

In [233]:
mmap = np.memmap('mymap', dtype='float64', shape=(10000, 10000))
mmap

memmap([[ 0.87261505, -0.43904416,  0.36104378, ..., -0.58223029,
          1.77299113, -0.06148116],
        [ 0.19793309,  2.54419456,  0.9167002 , ...,  0.17414909,
          0.8363528 , -0.64138733],
        [-0.86714563,  1.35076286,  0.00715899, ...,  0.08768643,
          1.79289497, -2.03982074],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]])

In [234]:
%xdel mmap

In [1]:
!del mymap

A.8.2 HDF5やその他の配列保存方法

## A.9 パフォーマンス改善のための豆知識

A.9.1 連続したメモリの重要性

In [3]:
import numpy as np

In [4]:
arr_c = np.ones((100, 10000), order='C')

In [5]:
arr_f = np.ones((100, 10000), order='F')

In [6]:
arr_c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [7]:
arr_f.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [8]:
arr_f.flags.f_contiguous

True

In [10]:
%timeit arr_c.sum(1)

531 µs ± 66.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [11]:
%timeit arr_f.sum(1)

405 µs ± 37.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [13]:
arr_f.copy('C').flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [14]:
arr_c[:50].flags.contiguous

True

In [15]:
arr_c[:, :50].flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False